name: "electrical_interface"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    paths:
      - 'Electrical/Design/INTERFACE/**'
      - '.github/workflows/electrical_interface.yml'
      - '.github/workflows/convert_bottom_position.py'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  FabPCB:
    name: PCB fabrication files
    runs-on: ubuntu-latest
    container: "setsoft/kicad_auto:ki7"

    steps:
    - uses: actions/checkout@v2

    - name: Run PCB stuff
      run: |
        make -C Electrical/Design/INTERFACE

    - name: Print errors
      if: ${{ always() }}
      run: |
        cat Electrical/Design/INTERFACE/mfg-bot/INTERFACE-drc.txt
        cat Electrical/Design/INTERFACE/kibot_error.log

    - name: Set Date
      run: echo "action_date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV

    - name: Convert position file
      run: |
        python3 .github/workflows/convert_bottom_position.py ../../Electrical/Design/INTERFACE/mfg-bot/mfg/INTERFACE-both_pos.csv ../../Electrical/Design/INTERFACE/mfg-bot/mfg/INTERFACE-both_pos_fixed.csv
        rm Electrical/Design/INTERFACE/mfg-bot/mfg/INTERFACE-both_pos.csv
  
    - name: Zipping gerber      
      uses: vimtor/action-zip@v1
      with:
        files: Electrical/Design/INTERFACE/mfg-bot/JLCPCB
        dest: "Electrical/Design/INTERFACE/mfg-bot/mfg/INTERFACE-gerber.zip"

    - name: Rename pdf files and removing non-zipped gerber files
      run: |
        mv Electrical/Design/INTERFACE/mfg-bot/INTERFACE-erc.txt Electrical/Design/INTERFACE/mfg-bot/INTERFACE_erc.txt
        mv Electrical/Design/INTERFACE/mfg-bot/INTERFACE-drc.txt Electrical/Design/INTERFACE/mfg-bot/INTERFACE_drc.txt
        mv Electrical/Design/INTERFACE/mfg-bot/Schematic.pdf Electrical/Design/INTERFACE/mfg-bot/INTERFACE_Schematic.pdf
        mv Electrical/Design/INTERFACE/mfg-bot/PCB_Top.pdf Electrical/Design/INTERFACE/mfg-bot/INTERFACE_PCB_Top.pdf
        mv Electrical/Design/INTERFACE/mfg-bot/PCB_Bottom.pdf Electrical/Design/INTERFACE/mfg-bot/INTERFACE_PCB_Bottom.pdf
        mv Electrical/Design/INTERFACE/kibot_error.log Electrical/Design/INTERFACE/mfg-bot/INTERFACE_kibot_error.log
        rm -r Electrical/Design/INTERFACE/mfg-bot/JLCPCB

    - name: Upload results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: FabPCB_Output
        path: |
          Electrical/Design/INTERFACE/mfg-bot/
        if-no-files-found: warn

    - name: Zipping artifacts      
      uses: vimtor/action-zip@v1
      with:
        files: Electrical/Design/INTERFACE/mfg-bot/
        dest: "INTERFACE_${{ env.action_date }}.zip"
        
    - uses: tsickert/discord-webhook@v4.0.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        content: "Heyo, fresh PCB files are ready!"
        filename: "INTERFACE_${{ env.action_date }}.zip"
        
    - name: Copy files to preview folder
      run: |
        mkdir -p Preview/Preview/Electrical && cp Electrical/Design/INTERFACE/mfg-bot/* Preview/Preview/Electrical

    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: preview # The branch name where you want to push the assets
        FOLDER: Preview # The directory where your assets are generated
        CLEAR_GLOBS_FILE: ".clear-target-files"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "Build: ({sha}) {msg}" # The commit message

