name: preview test

on:
  workflow_dispatch:

jobs:
  test-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Date
      run: echo "action_date=$(date +'%Y-%m-%d-%H%M')" >> Preview/test.txt

    - name: Configure Git
      run: |
        git checkout preview
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Commit Changes
      run: |
        git add Preview
        git commit -m "Committing changes to preview from GitHub Actions"
        git push origin preview